module Automation.BookReports.ReflectionUpdate
  ( booksSectionHeading
  , autoGeneratedMarker
  , buildBookWikilinkLine
  , insertOrUpdateBooksSection
  , reflectionContainsBookWikilink
  ) where

import Data.Text (Text)
import qualified Data.Text as T

import Automation.BookReports.Types (BookSlug, BookTitle, unBookSlug, unBookTitle)
import Automation.Wikilink (formatWikilink)

booksSectionHeading :: Text
booksSectionHeading = "## " <> formatWikilink "books/index" "📚 Books"

-- | Suffix appended to every auto-generated book wikilink so the orchestrator
-- can detect prior runs by scanning the reflection body — no separate flag needed.
autoGeneratedMarker :: Text
autoGeneratedMarker = "🤖"

buildBookWikilinkLine :: BookSlug -> BookTitle -> Text
buildBookWikilinkLine slug title =
  let target = "books/" <> unBookSlug slug
      alias  = unBookTitle title
  in "- 🆕📚 " <> formatWikilink target alias <> " " <> autoGeneratedMarker

reflectionContainsBookWikilink :: BookSlug -> Text -> Bool
reflectionContainsBookWikilink slug content =
  let needle = "[[books/" <> unBookSlug slug
  in needle `T.isInfixOf` content

-- | Insert a book wikilink under the Books section, creating the section if needed.
-- The section is placed before any trailing section (Updates / Changes / social embeds).
insertOrUpdateBooksSection
  :: [Text]      -- ^ trailing section headings (placed strictly after the books section)
  -> BookSlug
  -> BookTitle
  -> Text        -- ^ existing reflection content
  -> Text
insertOrUpdateBooksSection trailingHeadings slug title content
  | reflectionContainsBookWikilink slug content = content
  | sectionAlreadyPresent = appendUnderExistingSection content (buildBookWikilinkLine slug title)
  | otherwise             = insertFreshSection trailingHeadings content (buildBookWikilinkLine slug title)
  where
    sectionAlreadyPresent = T.isInfixOf booksSectionHeading content

appendUnderExistingSection :: Text -> Text -> Text
appendUnderExistingSection content newLine =
  let contentLines       = T.splitOn "\n" content
      sectionLineCount   = length (takeWhile (not . T.isPrefixOf booksSectionHeading) contentLines)
      (before, after)    = splitAt (sectionLineCount + 1) contentLines
      (existingItems, rest) = span (T.isPrefixOf "- ") after
  in T.intercalate "\n" (before <> existingItems <> [newLine] <> rest)

insertFreshSection :: [Text] -> Text -> Text -> Text
insertFreshSection trailingHeadings content newLine =
  let sectionBlock = booksSectionHeading <> "\n" <> newLine
  in case findFirstHeadingIndex trailingHeadings content of
       Just splitIndex ->
         let (before, after) = T.splitAt splitIndex content
         in T.stripEnd before <> "\n\n" <> sectionBlock <> "\n\n" <> after
       Nothing ->
         T.stripEnd content <> "\n\n" <> sectionBlock <> "\n"

findFirstHeadingIndex :: [Text] -> Text -> Maybe Int
findFirstHeadingIndex headings content =
  case filter (`T.isInfixOf` content) headings of
    [] -> Nothing
    matches ->
      Just (minimum (fmap (T.length . fst . (`T.breakOn` content)) matches))
