{-# LANGUAGE OverloadedStrings #-}

module Automation.BookReport
  ( BookReportResult (..)
  , defaultBookReportModel
  , defaultAmazonSearchModel
  , titleToKebabCase
  , extractAsin
  , buildAffiliateUrl
  , buildBookFrontmatter
  , buildBookBody
  , buildBookFileContent
  , booksSectionHeading
  , hasAutoGeneratedBookLink
  , insertBookLink
  , run
  ) where

import Automation.BookReport.Gemini
  ( buildReportPrompt
  , findBookMentionsWithGemini
  , generateBookReportWithGemini
  , searchAmazonProductUrl
  )
import Automation.Frontmatter (YamlValue (..), parseFrontmatter, quoteYamlValue, updateFrontmatterFields)
import Automation.InternalLinking (applyReplacements)
import Automation.InternalLinking.CandidateDiscovery (ContentEntry (..), buildContentIndex, findLinkCandidates)
import Automation.InternalLinking.LinkExtraction (bfsTraversal)
import Automation.InternalLinking.Masking (maskProtectedRegions)
import Automation.PacificTime (formatDay, todayPacificDay)
import Automation.RelativePath (mkRelativePath)
import Automation.Secret (Secret)
import Automation.Text (stripEmojis)
import Automation.Title (unTitle)
import qualified Automation.Gemini as Gemini
import Control.Concurrent (threadDelay)
import Control.Exception (SomeException, try)
import qualified Data.ByteString.Lazy as LBS
import qualified Data.Char as Char
import Data.List (find)
import Data.Maybe (fromMaybe, mapMaybe)
import qualified Data.Map.Strict as Map
import qualified Data.Set as Set
import Data.Text (Text)
import qualified Data.Text as T
import qualified Data.Text.Encoding as TE
import qualified Data.Text.IO as TIO
import Network.HTTP.Client
  ( Manager
  , parseRequest
  , requestHeaders
  , responseBody
  , responseStatus
  , httpLbs
  )
import Network.HTTP.Types.Status (statusCode)
import System.Directory (createDirectoryIfMissing, doesDirectoryExist, doesFileExist)
import System.FilePath ((</>))

data BookReportResult = BookReportResult
  { booksGenerated :: Int
  , booksAttempted :: Int
  , booksSkipped   :: Int
  } deriving (Show, Eq)

defaultBookReportModel :: Gemini.Model
defaultBookReportModel = Gemini.Gemini25Flash

defaultAmazonSearchModel :: Gemini.Model
defaultAmazonSearchModel = Gemini.Gemini25Flash

-- | Convert a book title to a URL-safe kebab-case slug.
-- Follows the same rules as the Obsidian Templater script:
--   lowercase → remove apostrophes → replace non-alphanumeric runs with "-" → trim dashes
titleToKebabCase :: Text -> Text
titleToKebabCase =
  trimDashes
    . T.pack
    . collapseConsecutiveDashes
    . map replaceNonAlphanumeric
    . T.unpack
    . T.filter (/= '\'')
    . T.toLower
  where
    replaceNonAlphanumeric character
      | Char.isAscii character && Char.isAlphaNum character = character
      | otherwise = '-'
    collapseConsecutiveDashes [] = []
    collapseConsecutiveDashes ('-' : '-' : rest) = collapseConsecutiveDashes ('-' : rest)
    collapseConsecutiveDashes (character : rest) = character : collapseConsecutiveDashes rest
    trimDashes = T.dropWhile (== '-') . T.dropWhileEnd (== '-')

-- | Extract an Amazon ASIN from a product URL.
-- Supports the /dp/ASIN and /gp/product/ASIN URL patterns.
extractAsin :: Text -> Maybe Text
extractAsin url
  | T.isInfixOf "/dp/" url =
      let segment = takeAsinSegment . T.drop 4 . snd $ T.breakOn "/dp/" url
      in if isValidAsin segment then Just segment else Nothing
  | T.isInfixOf "/gp/product/" url =
      let segment = takeAsinSegment . T.drop 12 . snd $ T.breakOn "/gp/product/" url
      in if isValidAsin segment then Just segment else Nothing
  | otherwise = Nothing

-- | Extract the ASIN-length segment by stopping at the first non-ASIN character.
takeAsinSegment :: Text -> Text
takeAsinSegment = T.takeWhile (\character -> Char.isAlphaNum character && character /= '?')

isValidAsin :: Text -> Bool
isValidAsin text = T.length text == 10 && T.all Char.isAlphaNum text

-- | Build an Amazon affiliate URL from an ASIN and associate tag.
buildAffiliateUrl :: Text -> Text -> Text
buildAffiliateUrl productAsin associateTag =
  "https://www.amazon.com/dp/" <> productAsin <> "?tag=" <> associateTag

-- | Build the YAML frontmatter block for a new book file.
-- Uses the emojified title (if provided) for the title and aliases fields.
buildBookFrontmatter :: Text -> Text -> Maybe Text -> Maybe Text -> Text
buildBookFrontmatter originalTitle slug mAffiliateLink mEmojifiedTitle =
  let displayTitle = fromMaybe originalTitle mEmojifiedTitle
      affiliateLines = case mAffiliateLink of
        Just link -> ["affiliate link: " <> link]
        Nothing   -> []
      baseLines =
        [ "---"
        , "share: true"
        , "aliases:"
        , "  - " <> quoteYamlValue displayTitle
        , "title: " <> quoteYamlValue displayTitle
        , "URL: " <> quoteYamlValue ("https://bagrounds.org/books/" <> slug)
        , "Author:"
        , "tags:"
        ]
  in T.intercalate "\n" (baseLines <> affiliateLines <> ["---"])

-- | Build the body of a book file, combining nav links, emojified title H1,
-- optional affiliate link, the generated report body, and the Gemini prompt attribution.
buildBookBody :: Text -> Text -> Maybe Text -> Maybe Text -> Gemini.Model -> Text
buildBookBody originalTitle reportBody mAffiliateLink mEmojifiedTitle model =
  let displayTitle = fromMaybe originalTitle mEmojifiedTitle
      plainTitle = T.strip (stripEmojis originalTitle)
      affiliateLinkLine = case mAffiliateLink of
        Just link -> "[🛒 " <> plainTitle <> ". As an Amazon Associate I earn from qualifying purchases.](" <> link <> ")\n\n"
        Nothing   -> ""
      prompt = buildReportPrompt originalTitle
  in T.intercalate "\n"
    [ "[[index|🏡 Home]] > [[/books/index|📚 Books]]"
    , "# " <> displayTitle
    , affiliateLinkLine
    , reportBody
    , ""
    , "## 💬 [Gemini](https://gemini.google.com) Prompt (" <> Gemini.modelToText model <> ")"
    , "> " <> prompt
    ]

-- | Assemble the complete book file content (frontmatter + body).
-- Parses the emojified title from the first non-empty line of the Gemini response.
buildBookFileContent :: Text -> Text -> Maybe Text -> Gemini.Model -> Text
buildBookFileContent originalTitle fullResponse mAffiliateLink model =
  let slug = titleToKebabCase originalTitle
      (mEmojifiedTitle, reportBody) = parseEmojifiedTitle fullResponse
      frontmatter = buildBookFrontmatter originalTitle slug mAffiliateLink mEmojifiedTitle
      body = buildBookBody originalTitle reportBody mAffiliateLink mEmojifiedTitle model
  in frontmatter <> "\n" <> body <> "\n"

-- | Parse the first non-empty line of a Gemini report response as the emojified title.
-- Returns (Just emojifiedTitle, remainingBody) if the first line looks like an emojified title,
-- otherwise returns (Nothing, fullResponse).
parseEmojifiedTitle :: Text -> (Maybe Text, Text)
parseEmojifiedTitle response =
  let allLines = T.lines response
      (_, rest) = span T.null allLines
  in case rest of
    (firstLine : remaining)
      | looksLikeEmojifiedTitle firstLine ->
          let bodyLines = dropWhile T.null remaining
          in (Just (T.strip firstLine), T.unlines bodyLines)
    _ -> (Nothing, response)
  where
    looksLikeEmojifiedTitle line =
      let stripped = T.strip line
      in not (T.isPrefixOf "#" stripped)
           && not (T.isPrefixOf "-" stripped)
           && not (T.null stripped)
           && T.length stripped < 200
           && hasLeadingEmoji stripped

    hasLeadingEmoji line =
      not (T.null line) && Char.ord (T.head line) > 127

-- | The section heading used in daily reflections for the book links section.
booksSectionHeading :: Text
booksSectionHeading = "## [[/books/index|📚 Books]]"

-- | Auto-generated book link marker used to distinguish automation-inserted links.
autoGeneratedMarker :: Text
autoGeneratedMarker = " 🤖"

-- | Detect whether the task already produced a book report in a given reflection.
-- Scans the page body for evidence: a list item starting with "- [[books/" and
-- ending with the auto-generated robot-emoji marker.
hasAutoGeneratedBookLink :: Text -> Bool
hasAutoGeneratedBookLink content =
  any isAutoBookLink (T.lines content)
  where
    isAutoBookLink line =
      T.isPrefixOf "- [[books/" line
        && T.isSuffixOf autoGeneratedMarker (T.strip line)

-- | Build the wikilink list item for a newly generated book in the reflection.
buildBookReflectionLink :: Text -> Text -> Text
buildBookReflectionLink bookSlug bookTitle =
  "- [[books/" <> bookSlug <> "|" <> bookTitle <> "]]" <> autoGeneratedMarker

-- | Insert a wikilink to a newly generated book into today's reflection content.
-- Creates a new "Books" section if one does not already exist, inserting it
-- before any trailing sections (social embeds, blog series sections, or changes).
-- Idempotent: no-op if the slug is already linked.
insertBookLink :: Text -> Text -> Text -> Text
insertBookLink reflectionContent bookSlug bookTitle =
  let bookLink = buildBookReflectionLink bookSlug bookTitle
  in if T.isInfixOf ("[[books/" <> bookSlug <> "|") reflectionContent
     then reflectionContent
     else if T.isInfixOf booksSectionHeading reflectionContent
       then appendToBookSection reflectionContent bookLink
       else insertBooksSection reflectionContent bookLink

appendToBookSection :: Text -> Text -> Text
appendToBookSection content bookLink =
  let contentLines = T.splitOn "\n" content
      sectionIndex = length (takeWhile (not . T.isPrefixOf booksSectionHeading) contentLines)
      (before, after) = splitAt (sectionIndex + 1) contentLines
      (listItems, rest) = span (T.isPrefixOf "- ") after
  in T.intercalate "\n" (before <> listItems <> [bookLink] <> rest)

-- | Static trailing section prefixes that the Books section should be inserted before.
trailingReflectionSectionPrefixes :: [Text]
trailingReflectionSectionPrefixes =
  [ "## 🔄 Updates"
  , "## [[changes/"
  , "## 🐦"
  , "## 🦋"
  , "## 🐘"
  ]

-- | Find the character index of the earliest trailing or auto-generated section
-- in the content, so the Books section can be inserted before it.
-- Trailing sections include social embeds, the changes section, and any
-- blog-series section headings (which look like "## [[<id>/index|...]]").
findEarliestInsertionPoint :: Text -> Maybe Int
findEarliestInsertionPoint content =
  let staticMatches =
        [ T.length (fst (T.breakOn prefix content))
        | prefix <- trailingReflectionSectionPrefixes
        , T.isInfixOf prefix content
        ]
      dynamicHeaders = filter isDynamicSeriesHeading (T.lines content)
      dynamicMatches =
        [ T.length (fst (T.breakOn header content))
        | header <- dynamicHeaders
        , T.isInfixOf header content
        ]
      allPositions = staticMatches <> dynamicMatches
  in case allPositions of
    [] -> Nothing
    _  -> Just (minimum allPositions)
  where
    isDynamicSeriesHeading line =
      T.isPrefixOf "## [[" line
        && T.isInfixOf "/index|" line
        && not (T.isPrefixOf booksSectionHeading line)

insertBooksSection :: Text -> Text -> Text
insertBooksSection content bookLink =
  let sectionBlock = booksSectionHeading <> "\n" <> bookLink
  in case findEarliestInsertionPoint content of
    Nothing ->
      T.stripEnd content <> "\n\n" <> sectionBlock <> "\n"
    Just insertionIndex ->
      let (before, after) = T.splitAt insertionIndex content
      in T.stripEnd before <> "\n\n" <> sectionBlock <> "\n\n" <> after

-- | Validate an Amazon affiliate URL by fetching it.
-- Returns True only when the page responds with HTTP 200; returns False otherwise.
-- Retries up to `urlValidationRetryCount` times (with exponential back-off) on
-- connection errors and transient server errors (429, 5xx) so that a single
-- rate-limit or momentary outage does not silently skip an otherwise valid URL.
-- A confirmed 404 (the URL does not exist) returns False immediately without
-- retrying. Any error after all retries are exhausted returns False so the
-- candidate is skipped rather than accepted on blind faith.
-- Also logs a warning when the page is reachable but the book title cannot be
-- found in the response body (possible wrong-page hit).
validateAffiliateUrl :: Manager -> Text -> Text -> IO Bool
validateAffiliateUrl manager affiliateUrl bookTitle = go 0
  where
    go attempt = do
      fetchResult <- try @SomeException $ do
        initReq <- parseRequest (T.unpack affiliateUrl)
        let httpReq = initReq
              { requestHeaders =
                  [ ("User-Agent", "Mozilla/5.0 (compatible; BookReport/1.0)")
                  , ("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")
                  ]
              }
        httpLbs httpReq manager
      case fetchResult of
        Left exception -> do
          putStrLn $ "  ⚠️  Affiliate URL fetch error (attempt " <> attemptLabel <> "): " <> show exception
          retryOrFail attempt "fetch error"
        Right response -> do
          let status = statusCode (responseStatus response)
          case status of
            404 -> do
              putStrLn "  ❌ Affiliate URL returned 404 — URL does not exist"
              pure False
            200 -> do
              let bodyText = T.toLower (TE.decodeUtf8 (LBS.toStrict (responseBody response)))
                  normalizedTitle = T.toLower (T.strip (stripEmojis bookTitle))
                  titleWords = filter ((> minimumTitleWordLength) . T.length) (T.words normalizedTitle)
                  titleConfirmed = not (null titleWords) && all (`T.isInfixOf` bodyText) titleWords
              if titleConfirmed
                then putStrLn "  ✅ Affiliate URL confirmed (title found on page)"
                else putStrLn "  ⚠️  Affiliate URL returned 200 but title not confirmed on page (proceeding)"
              pure True
            other -> do
              putStrLn $ "  ⚠️  Affiliate URL returned HTTP " <> show other <> " (attempt " <> attemptLabel <> ")"
              retryOrFail attempt ("HTTP " <> show other)
      where
        attemptLabel = show (attempt + 1) <> "/" <> show (urlValidationRetryCount + 1)
        retryOrFail currentAttempt reason =
          if currentAttempt < urlValidationRetryCount
            then do
              let delayMs = urlValidationBaseDelayMs * (2 ^ currentAttempt)
              putStrLn $ "  🔄 Retrying affiliate URL validation in " <> show delayMs <> " ms"
              threadDelay (delayMs * 1000)
              go (currentAttempt + 1)
            else do
              putStrLn $ "  ❌ Affiliate URL could not be confirmed after retries (" <> reason <> ") — skipping candidate"
              pure False

-- | Number of retry attempts for affiliate URL validation (after the initial attempt).
-- So the total attempts = urlValidationRetryCount + 1.
urlValidationRetryCount :: Int
urlValidationRetryCount = 3

-- | Base delay in milliseconds between retries (doubles on each attempt).
urlValidationBaseDelayMs :: Int
urlValidationBaseDelayMs = 2000

-- | Minimum length of a title word considered significant when matching the
-- book title against an Amazon page body. Words of two characters or fewer
-- (such as "a", "of", "to") are common to many titles and would produce
-- false positive matches if included.
minimumTitleWordLength :: Int
minimumTitleWordLength = 2

-- | The path to the books index file within the vault.
booksIndexFilePath :: FilePath -> FilePath
booksIndexFilePath vaultDir = vaultDir </> "books" </> "index.md"

-- | Pending state stored in the books index frontmatter between runs.
-- Written before any expensive API calls so a partially completed run
-- can resume even on a subsequent day (the books index is not date-scoped,
-- unlike the daily reflection file). The pending title identifies the book
-- being processed; the cached ASIN skips the Amazon search step on resume.
-- Both fields are cleared from the books index after a successful run.
data PendingBookState = PendingBookState
  { pendingTitle :: Text
  , cachedAsin   :: Maybe Text
  }

-- | A candidate book discovered during BFS scanning.
-- The title is the plain-text book title as found in the content.
-- The asin is populated only when resuming from a previous run that
-- already completed the Amazon search step.
-- The source is the relative path of the file where the title was found.
data BookCandidate = BookCandidate
  { candidateTitle  :: Text
  , candidateAsin   :: Maybe Text
  , candidateSource :: Text
  }

-- | Read any pending book state from the books index frontmatter.
-- The pending title and (optionally) its cached ASIN survive across day boundaries
-- because they are stored in the books index rather than in the daily reflection.
-- Returns Nothing if no pending work exists or if the book file was already created.
resolvePendingState :: Map.Map Text Text -> FilePath -> IO (Maybe PendingBookState)
resolvePendingState frontmatter vaultDir =
  case Map.lookup "book_report_pending" frontmatter of
    Nothing -> pure Nothing
    Just pending | T.null (T.strip pending) -> pure Nothing
    Just pendingTitle -> do
      let title = T.strip pendingTitle
          slug = titleToKebabCase title
          bookFilePath = vaultDir </> "books" </> T.unpack slug <> ".md"
      alreadyExists <- doesFileExist bookFilePath
      if alreadyExists
        then pure Nothing
        else do
          let mAsin = Map.lookup "book_report_asin" frontmatter
                >>= \rawAsin -> if T.null (T.strip rawAsin) then Nothing else Just (T.strip rawAsin)
          pure (Just PendingBookState { pendingTitle = title, cachedAsin = mAsin })

-- | Main entry point. Checks for a pending book from a previous partial run,
-- then BFS-scans content for unlinked book mentions if no pending title is found.
-- Refuses to run if AMAZON_ASSOCIATE_TAG is not set to prevent generating
-- book pages without affiliate links.
-- Idempotency is detected by scanning the reflection for evidence (a 🤖-marked
-- book link), not by relying on a frontmatter flag.
-- Pending title and cached ASIN are stored in the books index frontmatter so
-- they persist across day boundaries if the task cannot finish the same day.
run :: Manager -> Secret -> Text -> FilePath -> IO BookReportResult
run manager apiKey associateTag vaultDir
  | T.null associateTag = do
      putStrLn "  🚫 AMAZON_ASSOCIATE_TAG not set — refusing to generate book reports without affiliate links"
      pure BookReportResult { booksGenerated = 0, booksAttempted = 0, booksSkipped = 1 }
  | otherwise = do
      today <- todayPacificDay
      let todayText = formatDay today
          reflectionPath = vaultDir </> "reflections" </> T.unpack todayText <> ".md"
          booksIndex = booksIndexFilePath vaultDir

      reflectionExists <- doesFileExist reflectionPath
      mReflectionContent <-
        if reflectionExists
          then Just <$> TIO.readFile reflectionPath
          else pure Nothing

      -- Idempotency: detect by page evidence — look for a 🤖-marked book link
      -- in the reflection body rather than relying on a frontmatter flag.
      let reflectionAlreadyHasBookLink = maybe False hasAutoGeneratedBookLink mReflectionContent
      if reflectionAlreadyHasBookLink
        then do
          putStrLn "  ⏭️  Reflection already contains an auto-generated book link — skipping"
          pure BookReportResult { booksGenerated = 0, booksAttempted = 0, booksSkipped = 1 }
        else do
          let booksDir = vaultDir </> "books"
          booksDirExists <- doesDirectoryExist booksDir
          if not booksDirExists
            then do
              putStrLn "  ⚠️  Books directory not found — skipping"
              pure BookReportResult { booksGenerated = 0, booksAttempted = 0, booksSkipped = 1 }
            else do
              existingBooks <- buildContentIndex vaultDir
              let existingNormalizedTitles = Set.fromList
                    (map (normalizeTitleForComparison . unTitle . plainTitle) existingBooks)
              putStrLn $ "  📚 Existing books: " <> show (length existingBooks)

              -- Read the books index to check for pending state that survived from a
              -- previous (possibly different-day) run.
              booksIndexExists <- doesFileExist booksIndex
              booksIndexFrontmatter <-
                if booksIndexExists
                  then fst . parseFrontmatter <$> TIO.readFile booksIndex
                  else pure Map.empty

              mPendingState <- resolvePendingState booksIndexFrontmatter vaultDir

              candidates <- case mPendingState of
                Just state -> do
                  putStrLn $ "  📌 Resuming with pending book: " <> T.unpack (pendingTitle state)
                  case cachedAsin state of
                    Just resumedAsin -> putStrLn $ "  💾 Using cached ASIN: " <> T.unpack resumedAsin
                    Nothing          -> pure ()
                  pure [ BookCandidate
                           { candidateTitle  = pendingTitle state
                           , candidateAsin   = cachedAsin state
                           , candidateSource = "<pending>"
                           } ]
                Nothing -> do
                  allFiles <- bfsTraversal vaultDir
                  putStrLn $ "  🔍 BFS: " <> show (length allFiles) <> " files reachable"
                  findFirstCandidates manager apiKey vaultDir existingBooks allFiles existingNormalizedTitles todayText

              case candidates of
                [] -> do
                  putStrLn "  📭 No new book candidates found"
                  pure BookReportResult { booksGenerated = 0, booksAttempted = 0, booksSkipped = 0 }
                _ -> do
                  putStrLn $ T.unpack
                    (  "  📋 Found " <> T.pack (show (length candidates)) <> " book candidate(s): "
                    <> T.intercalate ", " (map candidateTitle (take 3 candidates))
                    )
                  tryGenerateReport manager apiKey associateTag vaultDir reflectionPath booksIndex todayText candidates 0

-- | BFS through content files, scanning ONE file for plain-text book mentions.
-- Skips files that have already been scanned (detected by the book_mention_scanned
-- frontmatter field having any value). The scan is permanent — a scanned file is
-- never re-scanned by a future run.
-- After scanning, writes book_mention_scanned: <date> to the file's own frontmatter.
-- Also inserts wikilinks for books that are mentioned but already have pages.
-- Returns a list of BookCandidate values; candidateAsin is always Nothing for
-- newly discovered candidates (only set when resuming from pending state).
findFirstCandidates :: Manager -> Secret -> FilePath -> [ContentEntry] -> [Text] -> Set.Set Text -> Text -> IO [BookCandidate]
findFirstCandidates manager apiKey vaultDir existingBooks allFiles existingNormalizedTitles todayText =
  go allFiles []
  where
    go [] accumulator = pure accumulator
    go (relPath : rest) accumulator = do
      let filePath = vaultDir </> T.unpack relPath
      exists <- doesFileExist filePath
      if not exists
        then go rest accumulator
        else do
          content <- TIO.readFile filePath
          let (frontmatter, body) = parseFrontmatter content
          -- Skip files already scanned today to avoid redundant Gemini calls on retry
          case Map.lookup "book_mention_scanned" frontmatter of
            Just _ -> do
              putStrLn $ "  ⏭️  Already scanned (permanent): " <> T.unpack relPath
              go rest accumulator
            _ -> do
              putStrLn $ "  🔎 Scanning for book mentions: " <> T.unpack relPath
              result <- findBookMentionsWithGemini manager apiKey defaultBookReportModel body
              case result of
                Left err -> do
                  putStrLn $ "  ⚠️  Gemini error scanning " <> T.unpack relPath <> ": " <> T.unpack err
                  go rest accumulator
                Right mentions -> do
                  -- Record the scan date permanently so this file is never re-scanned.
                  updateFrontmatterFields filePath [("book_mention_scanned", YamlText todayText)]
                  let newBooks = filter (\t -> not (Set.member (normalizeTitleForComparison t) existingNormalizedTitles)) mentions
                      existingMentioned = filter (\t -> Set.member (normalizeTitleForComparison t) existingNormalizedTitles) mentions
                  putStrLn $ "  📖 " <> T.unpack relPath <> ": " <> show (length mentions) <> " mention(s), "
                    <> show (length newBooks) <> " new, " <> show (length existingMentioned) <> " already have pages"
                  insertWikilinksForExistingMentions relPath filePath existingBooks existingMentioned
                  let candidates = map (\title -> BookCandidate { candidateTitle = title, candidateAsin = Nothing, candidateSource = relPath }) newBooks
                  if null candidates
                    then go rest accumulator
                    else pure (accumulator <> candidates)

-- | Insert wikilinks for books that are mentioned in plain text but already have pages.
-- Reuses the existing InternalLinking infrastructure (findLinkCandidates + applyReplacements).
insertWikilinksForExistingMentions :: Text -> FilePath -> [ContentEntry] -> [Text] -> IO ()
insertWikilinksForExistingMentions relPath filePath existingBooks mentionedTitles =
  case mkRelativePath relPath of
    Left _ -> pure ()
    Right selfRelPath -> do
      let matchingEntries = mapMaybe (`findEntryForTitle` existingBooks) mentionedTitles
      case matchingEntries of
        [] -> pure ()
        _ -> do
          content <- TIO.readFile filePath
          let masked = maskProtectedRegions content
              candidates = findLinkCandidates matchingEntries content masked selfRelPath
          case candidates of
            [] -> pure ()
            _ -> do
              let updated = applyReplacements content candidates (replicate (length candidates) True)
              TIO.writeFile filePath updated
              putStrLn $ "  🔗 " <> T.unpack relPath <> ": inserted "
                <> show (length candidates) <> " wikilink(s) for existing book(s)"

findEntryForTitle :: Text -> [ContentEntry] -> Maybe ContentEntry
findEntryForTitle mentionedTitle =
  find (\e -> normalizeTitleForComparison (unTitle (plainTitle e)) == normalizeTitleForComparison mentionedTitle)

normalizeTitleForComparison :: Text -> Text
normalizeTitleForComparison = T.toLower . T.strip . stripEmojis

-- | Try to generate a book report for the first candidate that successfully
-- passes Amazon search and URL validation.
-- BookCandidate.candidateAsin is set when resuming from a pending state where
-- Amazon search already completed; Nothing for freshly discovered candidates.
-- Pending state is stored in the books index frontmatter (not the reflection)
-- so it persists across day boundaries.
-- On success clears book_report_pending and book_report_asin from the books index.
tryGenerateReport :: Manager -> Secret -> Text -> FilePath -> FilePath -> FilePath -> Text -> [BookCandidate] -> Int -> IO BookReportResult
tryGenerateReport _ _ _ _ _ _ _ [] attempted =
  pure BookReportResult { booksGenerated = 0, booksAttempted = attempted, booksSkipped = 0 }
tryGenerateReport manager apiKey associateTag vaultDir reflectionPath booksIndex todayText (candidate : rest) attempted = do
  let bookTitle = candidateTitle candidate
  -- Persist the candidate title in the books index before any expensive API calls.
  -- Using the books index (not the daily reflection) means this survives across days.
  updateFrontmatterFields booksIndex [("book_report_pending", YamlText bookTitle)]

  mAsin <- case candidateAsin candidate of
    Just resumedAsin -> do
      putStrLn $ "  💾 Reusing cached ASIN: " <> T.unpack resumedAsin
      pure (Just resumedAsin)
    Nothing -> do
      putStrLn $ "  🔍 Searching Amazon for: " <> T.unpack bookTitle
      mAmazonUrl <- searchAmazonProductUrl manager apiKey defaultAmazonSearchModel bookTitle
      case mAmazonUrl of
        Nothing -> do
          putStrLn $ "  ⏭️  Amazon URL not found for: " <> T.unpack bookTitle <> " — trying next"
          pure Nothing
        Just amazonUrl -> do
          putStrLn $ "  🛒 Amazon URL: " <> T.unpack amazonUrl
          let mExtractedAsin = extractAsin amazonUrl
          case mExtractedAsin of
            Nothing -> do
              putStrLn "  ⚠️  Could not extract ASIN from URL — trying next"
              pure Nothing
            Just extractedAsin -> do
              let affiliateUrl = buildAffiliateUrl extractedAsin associateTag
              putStrLn $ "  💰 Affiliate URL: " <> T.unpack affiliateUrl
              -- Validate the URL before committing to this candidate
              urlValid <- validateAffiliateUrl manager affiliateUrl bookTitle
              if not urlValid
                then do
                  putStrLn "  ❌ Affiliate URL invalid — trying next candidate"
                  pure Nothing
                else do
                  -- Cache the ASIN so a retry skips the Amazon search step
                  updateFrontmatterFields booksIndex [("book_report_asin", YamlText extractedAsin)]
                  pure (Just extractedAsin)

  case mAsin of
    Nothing ->
      tryGenerateReport manager apiKey associateTag vaultDir reflectionPath booksIndex todayText rest (attempted + 1)
    Just productAsin -> do
      let affiliateLink = buildAffiliateUrl productAsin associateTag
      putStrLn $ "  📝 Generating book report for: " <> T.unpack bookTitle
      reportResult <- generateBookReportWithGemini manager apiKey defaultBookReportModel bookTitle
      case reportResult of
        Left err -> do
          putStrLn $ "  ❌ Report generation failed for " <> T.unpack bookTitle <> ": " <> T.unpack err
          tryGenerateReport manager apiKey associateTag vaultDir reflectionPath booksIndex todayText rest (attempted + 1)
        Right fullResponse -> do
          let slug = titleToKebabCase bookTitle
              bookFilename = slug <> ".md"
              booksDir = vaultDir </> "books"
              bookFilePath = booksDir </> T.unpack bookFilename
          alreadyExists <- doesFileExist bookFilePath
          if alreadyExists
            then do
              putStrLn $ "  ⏭️  Book file already exists: " <> T.unpack bookFilename
              pure BookReportResult { booksGenerated = 0, booksAttempted = attempted + 1, booksSkipped = 1 }
            else do
              createDirectoryIfMissing True booksDir
              let fileContent = buildBookFileContent bookTitle fullResponse (Just affiliateLink) defaultBookReportModel
              TIO.writeFile bookFilePath fileContent
              putStrLn $ "  ✅ Created: books/" <> T.unpack bookFilename

              -- Add 🤖-marked book link to today's reflection (this is the page evidence
              -- that the idempotency check scans for on the next run).
              reflectionExists <- doesFileExist reflectionPath
              if reflectionExists
                then do
                  reflectionContent <- TIO.readFile reflectionPath
                  let updatedReflection = insertBookLink reflectionContent slug bookTitle
                  TIO.writeFile reflectionPath updatedReflection
                  putStrLn $ "  📓 Added book link to reflection: " <> T.unpack todayText
                else
                  putStrLn $ "  ⚠️  No reflection found for today (" <> T.unpack todayText <> ") — skipping reflection link"

              -- Clear the pending state from the books index now that the report is done.
              updateFrontmatterFields booksIndex
                [ ("book_report_pending", YamlText "")
                , ("book_report_asin",    YamlText "")
                ]
              putStrLn "  🧹 Cleared pending state from books index"

              pure BookReportResult { booksGenerated = 1, booksAttempted = attempted + 1, booksSkipped = 0 }

