/**
 * AI text generation via Google Gemini.
 *
 * The model generates ONLY creative content (topic tags, discussion questions).
 * Deterministic parts (title, URL, formatting) are assembled in code via
 * the variant's PostAssembler from prompts.ts.
 *
 * Dual-model architecture:
 * - Tags: Generated by the primary model (Gemma — smaller, faster, sufficient for tags)
 * - Questions: Generated by Gemini 3.1 Flash Lite (higher rate limits, better question quality)
 *
 * For variant B, two model calls are made in parallel:
 * 1. Tags via prompt A using the primary (tags) model
 * 2. Question via prompt B using the question model
 * This guarantees the only difference between A and B is the added question.
 *
 * Rate limit handling:
 * When the API returns 429 (RESOURCE_EXHAUSTED), the retry logic parses
 * the `retryDelay` from the error details and waits before retrying.
 * Exponential backoff is used as a fallback when no explicit delay is provided.
 *
 * @module gemini
 */

import type { ReflectionData } from "./types.ts";
import type { VariantId } from "./experiment.ts";
import { DEFAULT_GEMINI_MODEL, DEFAULT_QUESTION_MODEL } from "./types.ts";
import { buildPromptForVariant, assemblePostForVariant, type PromptPair } from "./prompts.ts";

/** Maximum number of retries for rate-limited requests. */
const MAX_RETRIES = 3;

/** Default backoff delay in ms when no Retry-After is provided. */
const DEFAULT_BACKOFF_MS = 5_000;

/** Maximum backoff delay in ms. */
const MAX_BACKOFF_MS = 60_000;

/**
 * Parse a retry delay from a Gemini API 429 error.
 *
 * The API can return a `retryDelay` in the error details as a string like "14s".
 * Returns the delay in milliseconds, or null if not parseable.
 */
export function parseRetryDelay(error: unknown): number | null {
  if (!error || typeof error !== "object") return null;

  // The @google/generative-ai SDK wraps the API error.
  // Try to find retryDelay in error message (often includes the JSON details)
  const message = (error as { message?: string }).message ?? "";

  // Pattern: retryDelay "Xs" or retryDelay: "Xs" in the error message or details
  const delayMatch = message.match(/retryDelay["\s:]*["']?(\d+)s/i);
  if (delayMatch) {
    return parseInt(delayMatch[1]!, 10) * 1000;
  }

  // Try to parse from error details if available (structured error)
  const details = (error as { errorDetails?: Array<{ retryDelay?: string }> }).errorDetails;
  if (Array.isArray(details)) {
    for (const detail of details) {
      if (detail.retryDelay) {
        const match = detail.retryDelay.match(/(\d+)s/);
        if (match) return parseInt(match[1]!, 10) * 1000;
      }
    }
  }

  // Retry-After header value (some errors surface this)
  const retryAfter = (error as { headers?: Record<string, string> }).headers?.["retry-after"];
  if (retryAfter) {
    const seconds = parseInt(retryAfter, 10);
    if (!isNaN(seconds)) return seconds * 1000;
  }

  return null;
}

/**
 * Check if an error is a rate limit (429 / RESOURCE_EXHAUSTED) error.
 */
export function isRateLimitError(error: unknown): boolean {
  if (!error || typeof error !== "object") return false;

  const message = (error as { message?: string }).message ?? "";
  const status = (error as { status?: number }).status;

  return (
    status === 429 ||
    message.includes("429") ||
    message.includes("RESOURCE_EXHAUSTED") ||
    message.includes("quota")
  );
}

/**
 * Build the prompt for Gemini to generate a social media post.
 * Pure function — constructs the prompt from reflection data.
 *
 * @deprecated Use buildPromptForVariant from prompts.ts for A/B testing.
 * Retained for backward compatibility.
 */
export function buildGeminiPrompt(reflection: ReflectionData): PromptPair {
  return buildPromptForVariant("A", reflection);
}

/**
 * Call the Gemini model with a prompt and return the trimmed text output.
 * Includes rate limit retry with exponential backoff.
 *
 * When the API returns 429 (RESOURCE_EXHAUSTED), parses the retryDelay
 * from the error and waits before retrying. Falls back to exponential
 * backoff if no explicit delay is provided.
 */
async function callGemini(
  model: { generateContent: (req: unknown) => Promise<{ response: { text: () => string } }> },
  prompt: PromptPair,
  modelLabel: string = "model",
): Promise<string> {
  let backoffMs = DEFAULT_BACKOFF_MS;

  for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
    try {
      const result = await model.generateContent({
        contents: [
          {
            role: "user",
            parts: [{ text: `${prompt.system}\n\n${prompt.user}` }],
          },
        ],
      });
      return result.response.text().trim();
    } catch (error) {
      if (isRateLimitError(error) && attempt < MAX_RETRIES) {
        const serverDelay = parseRetryDelay(error);
        const waitMs = serverDelay ?? backoffMs;
        console.warn(
          `⏳ Rate limit hit on ${modelLabel} (attempt ${attempt + 1}/${MAX_RETRIES + 1}). ` +
          `Waiting ${(waitMs / 1000).toFixed(1)}s before retry...`,
        );
        await new Promise((resolve) => setTimeout(resolve, waitMs));
        backoffMs = Math.min(backoffMs * 2, MAX_BACKOFF_MS);
        continue;
      }
      throw error;
    }
  }

  // Unreachable, but satisfies TypeScript
  throw new Error(`Exceeded ${MAX_RETRIES} retries for ${modelLabel}`);
}

/**
 * Generate post text using Google Gemini API.
 *
 * Dual-model architecture:
 * - Tags (prompt A): generated by the primary model (e.g. Gemma)
 * - Questions (prompt B): generated by the question model (e.g. Gemini 3.1 Flash Lite)
 *
 * The assembler deterministically injects creative parts into the final post
 * alongside the title and URL.
 *
 * For variant B, two calls are made in parallel:
 * 1. Tags via prompt A using tagsModelName (same tags as an A post would get)
 * 2. Question via prompt B using questionModelName
 * The outputs are combined for the assembler.
 *
 * Platform-specific length limits are enforced by each platform's
 * posting task via fitPostToLimit(), not here.
 */
export async function generateTweetWithGemini(
  reflection: ReflectionData,
  apiKey: string,
  tagsModelName: string = DEFAULT_GEMINI_MODEL,
  variant: VariantId = "A",
  questionModelName: string = DEFAULT_QUESTION_MODEL,
): Promise<string> {
  const { GoogleGenerativeAI } = await import("@google/generative-ai");
  const genAI = new GoogleGenerativeAI(apiKey);

  let modelOutput: string;

  if (variant === "B") {
    // Variant B: two parallel calls with different models
    // Tags: primary model (same as variant A would use)
    // Question: question model (Gemini Flash Lite — higher rate limits, better quality)
    const tagsModel = genAI.getGenerativeModel({ model: tagsModelName });
    const questionModel = genAI.getGenerativeModel({ model: questionModelName });

    const tagsPrompt = buildPromptForVariant("A", reflection);
    const questionPrompt = buildPromptForVariant("B", reflection);

    console.log(`  🏷️ Tags model: ${tagsModelName}`);
    console.log(`  ❓ Question model: ${questionModelName}`);

    const [tags, question] = await Promise.all([
      callGemini(tagsModel, tagsPrompt, `tags/${tagsModelName}`),
      callGemini(questionModel, questionPrompt, `question/${questionModelName}`),
    ]);

    // Combine as "question\ntags" for the assembler's parseVariantBOutput
    modelOutput = `${question}\n${tags}`;
  } else {
    // Variant A: single call for tags using primary model
    const model = genAI.getGenerativeModel({ model: tagsModelName });
    const prompt = buildPromptForVariant(variant, reflection);
    modelOutput = await callGemini(model, prompt, `tags/${tagsModelName}`);
  }

  // Assemble the final post deterministically from creative parts + title/URL
  const text = assemblePostForVariant(variant, modelOutput, reflection);

  return text;
}
