/**
 * AI text generation via Google Gemini.
 *
 * The model generates ONLY creative content (topic tags, discussion questions).
 * Deterministic parts (title, URL, formatting) are assembled in code via
 * the PostAssembler from prompts.ts.
 *
 * Dual-model architecture:
 * - Tags: Generated by the primary model (Gemma — smaller, faster, sufficient for tags)
 * - Questions: Generated by the question model (Gemini Flash Lite — higher rate limits)
 *
 * Two model calls are made in parallel:
 * 1. Tags via the tags model
 * 2. Question via the question model
 *
 * Rate limit handling:
 * When the API returns 429 (RESOURCE_EXHAUSTED), the retry logic parses
 * the `retryDelay` from the error details and waits before retrying.
 * Exponential backoff is used as a fallback when no explicit delay is provided.
 *
 * @module gemini
 */

import type { ReflectionData } from "./types.ts";
import { DEFAULT_GEMINI_MODEL, DEFAULT_QUESTION_MODEL, BLUESKY_MAX_LENGTH } from "./types.ts";
import {
  buildTagsPrompt,
  buildQuestionPrompt,
  assemblePost,
  buildShortenQuestionPrompt,
  type PromptPair,
} from "./prompts.ts";
import { countGraphemes } from "./text.ts";

const MAX_RETRIES = 3;
const DEFAULT_BACKOFF_MS = 5_000;
const MAX_BACKOFF_MS = 60_000;

export function parseRetryDelay(error: unknown): number | null {
  if (!error || typeof error !== "object") return null;

  const message = (error as { message?: string }).message ?? "";

  const delayMatch = message.match(/retryDelay["\s:]*["']?(\d+)s/i);
  if (delayMatch) {
    return parseInt(delayMatch[1]!, 10) * 1000;
  }

  const details = (error as { errorDetails?: Array<{ retryDelay?: string }> }).errorDetails;
  if (Array.isArray(details)) {
    for (const detail of details) {
      if (detail.retryDelay) {
        const match = detail.retryDelay.match(/(\d+)s/);
        if (match) return parseInt(match[1]!, 10) * 1000;
      }
    }
  }

  const retryAfter = (error as { headers?: Record<string, string> }).headers?.["retry-after"];
  if (retryAfter) {
    const seconds = parseInt(retryAfter, 10);
    if (!isNaN(seconds)) return seconds * 1000;
  }

  return null;
}

export function isRateLimitError(error: unknown): boolean {
  if (!error || typeof error !== "object") return false;

  const message = (error as { message?: string }).message ?? "";
  const status = (error as { status?: number }).status;

  return (
    status === 429 ||
    message.includes("429") ||
    message.includes("RESOURCE_EXHAUSTED") ||
    message.includes("quota")
  );
}

/**
 * @deprecated Use buildTagsPrompt from prompts.ts directly.
 */
export function buildGeminiPrompt(reflection: ReflectionData): PromptPair {
  return buildTagsPrompt(reflection);
}

async function callGemini(
  model: { generateContent: (req: unknown) => Promise<{ response: { text: () => string } }> },
  prompt: PromptPair,
  modelLabel: string = "model",
): Promise<string> {
  let backoffMs = DEFAULT_BACKOFF_MS;

  for (let attempt = 0; attempt <= MAX_RETRIES; attempt++) {
    try {
      const result = await model.generateContent({
        contents: [
          {
            role: "user",
            parts: [{ text: `${prompt.system}\n\n${prompt.user}` }],
          },
        ],
      });
      return result.response.text().trim();
    } catch (error) {
      if (isRateLimitError(error) && attempt < MAX_RETRIES) {
        const serverDelay = parseRetryDelay(error);
        const waitMs = serverDelay ?? backoffMs;
        console.warn(
          `⏳ Rate limit hit on ${modelLabel} (attempt ${attempt + 1}/${MAX_RETRIES + 1}). ` +
          `Waiting ${(waitMs / 1000).toFixed(1)}s before retry...`,
        );
        await new Promise((resolve) => setTimeout(resolve, waitMs));
        backoffMs = Math.min(backoffMs * 2, MAX_BACKOFF_MS);
        continue;
      }
      throw error;
    }
  }

  throw new Error(`Exceeded ${MAX_RETRIES} retries for ${modelLabel}`);
}

export async function generatePostWithGemini(
  reflection: ReflectionData,
  apiKey: string,
  tagsModelName: string = DEFAULT_GEMINI_MODEL,
  questionModelName: string = DEFAULT_QUESTION_MODEL,
): Promise<string> {
  const { GoogleGenerativeAI } = await import("@google/generative-ai");
  const genAI = new GoogleGenerativeAI(apiKey);

  const tagsModel = genAI.getGenerativeModel({ model: tagsModelName });
  const questionModel = genAI.getGenerativeModel({ model: questionModelName });

  const tagsPrompt = buildTagsPrompt(reflection);
  const questionPrompt = buildQuestionPrompt(reflection);

  console.log(`  🏷️ Tags model: ${tagsModelName}`);
  console.log(`  ❓ Question model: ${questionModelName}`);

  const [tags, question] = await Promise.all([
    callGemini(tagsModel, tagsPrompt, `tags/${tagsModelName}`),
    callGemini(questionModel, questionPrompt, `question/${questionModelName}`),
  ]);

  const modelOutput = `${question}\n${tags}`;

  let text = assemblePost(modelOutput, reflection);
  const overage = countGraphemes(text) - BLUESKY_MAX_LENGTH;

  if (overage > 0) {
    const SHORTEN_SAFETY_BUFFER = 10;
    console.log(`  ✂️ Post exceeds Bluesky limit by ${overage} graphemes — asking LLM to shorten question...`);
    const shortenPrompt = buildShortenQuestionPrompt(question, overage + SHORTEN_SAFETY_BUFFER);
    const shortenedQuestion = await callGemini(questionModel, shortenPrompt, `shorten/${questionModelName}`);
    const shortenedOutput = `${shortenedQuestion.trim()}\n${tags}`;
    text = assemblePost(shortenedOutput, reflection);
    console.log(`  ✅ Shortened: ${countGraphemes(text)} graphemes (was ${countGraphemes(assemblePost(modelOutput, reflection))})`);
  }

  return text;
}
